### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by anukaal**
updated with the latest version pf pyparsing with `pyparsing==2.4.7`

### CODE REVIEW

**Comment by rwgk** [comment]
Hi @anukaal, I just rebased this PR on current `main` and triggered the CI. Waiting for the results.

**Comment by rwgk** [comment]
CI is green, but I don't know if the changes actually had any effect. I see this in one of the logs:
```
2021-09-30T01:01:54.5426049Z #7 [ 4/10] RUN apt-get update && apt-get install -y     clang-11     libclang-11-dev     libgoogle-glog-dev     libgtest-dev     libllvm11     llvm-11-dev     python3-dev     python3-pyparsing     zlib1g-dev
2021-09-30T01:01:54.5427142Z #7 CACHED
```

Does the `pyparsing==2.4.7` change make a difference in your environment?

Note that I don't know much about setup.py. Tagging @akekawit who may know more.

**Comment by akekawit** [comment]
requirements.txt is only used in our experimental Bazel build, so at the moment this change has no effect. setup.py (https://github.com/google/clif/blob/main/setup.py#L80) is used in our Examples workflow (via INSTALL.sh). Our CI workflow unfortunately doesn't use setup.py but relies on setting PYTHONPATH in Cmake, which uses the python3-pyparsing in the Dockerfile. We probably need to unify these...

Regardless, from what I can remember, there were some differences between 2.2.0 and 2.4.7 that cause pyclif to fail to parse .clif file due to indentation errors.

**Comment by rwgk** [comment]
Closing for now. Sorry, modernizing pyparsing is not straightforward and not a priority at the moment.

**Pull request closed without merging**
