### PR TITLE
Correct link from examples readme to Python primer

### PR DESCRIPTION
**Pull request by altendky**
I see you don't take contributions, but just in case...

### CODE REVIEW

**Comment by altendky** [comment]
I signed it!

**Comment by mrovner** [comment]
Thank you for the patch.
The only problem I see the README.md is currently "optimized" for online viewing on github site.
AFAIU the patch makes it work after installation "optimizing" for offline-viewing.
I'm afraid that applying the patch will ruin the online viewing. If that's true this file modification should be a part of the install process.

**Comment by altendky** [comment]
I only forked and patched because the link was broken while browsing GitHub.

Broken: https://github.com/google/clif/tree/master/examples
Working: https://github.com/altendky/clif/tree/patch-1/examples

I just additionally tried in incognito, another 'person' I have configured in Chrome', and had a friend try.  All with the same results.

I'm unsure how cloning this would change any relative paths.  Though, certainly, installing it could move stuff around.  Would be nice if the install were integrated into `setup.py` so you could `pip` it directly.

**Comment by mrovner** [comment]
Oops, I was mistaken /readme with /examples/readme. Sorry for the confusion.

**Pull request merged**
